var etsyItems = {
"count": 50100,
"results": [
{
"listing_id": 234762161,
"state": "active",
"user_id": 63500342,
"category_id": 68892008,
"title": "65&quot; Double Blooming Green Macrame Plant Hanger Hanging Basket Planter #496",
"description": "65&quot; Double Blooming Green Butterfly Macrame Hanging Planter\nPerfect for Plants or Flowers, 4 arm braided polyolefin cords\nBlooming double plant hanger style with cute matching speckled acrylic butterflies and tan wood barrel accent beads. Size from top of ring to bottom of tassel is about 65 inches.\nPot Size up to 10&quot; in diameter depending on pot style for both sections.Listing is for Plant hanger only, pot/basket not included! item#496",
"creation_tsz": 1432661424,
"ending_tsz": 1443288624,
"original_creation_tsz": 1432661424,
"last_modified_tsz": 1432661425,
"price": "65.00",
"currency_code": "USD",
"quantity": 1,
"tags": [
"Macrame",
"Plant Hangers",
"Hanging baskets",
"Planters",
"Home Decor",
"Hanging Planters",
"Macrame Plant Hanger",
"Macrame Planters",
"Home and Garden",
"Decorative planters",
"plants pot holder",
"double plant hanger",
"double planter"
],
"category_path": [
"Housewares",
"Home Decor"
],
"category_path_ids": [
69150425,
68892008
],
"materials": [
"macrame cord",
"metal hanging ring",
"green cords",
"braided macrame cord",
"beads",
"butterfly acrylic beads"
],
"shop_section_id": 17171462,
"featured_rank": null,
"state_tsz": 1432661424,
"url": "https://www.etsy.com/listing/234762161/65-double-blooming-green-macrame-plant?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 1,
"num_favorers": 0,
"shipping_template_id": 11490975055,
"processing_min": 1,
"processing_max": 3,
"who_made": "i_did",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": "77",
"item_weight_units": null,
"item_length": "13",
"item_width": "10",
"item_height": "2",
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 1002,
"taxonomy_path": [
"Home & Living",
"Home Décor"
],
"used_manufacturer": false
},
{
"listing_id": 219439470,
"state": "active",
"user_id": 10834240,
"category_id": 68890874,
"title": "Flying Wooden Folk Art Seagull",
"description": "A vintage folk art flying seagull. The wings move up and down and are attached to a piece of wood with clear line. \r\n\r\nThe piece is hand painted and the wing feathers look like the detail is done with a pencil. There are some scuffs but the seagull is otherwise in good vintage condition. \r\n\r\nMeasures 12 3/4&quot; long.",
"creation_tsz": 1432661406,
"ending_tsz": 1443288606,
"original_creation_tsz": 1421867440,
"last_modified_tsz": 1432661406,
"price": "38.00",
"currency_code": "USD",
"quantity": 1,
"tags": [
"wood carving cutout",
"homemade art",
"artistic",
"motion flapping",
"garden decor",
"porch patio",
"bird ocean breeze",
"hand painted",
"wood working",
"Americana",
"American"
],
"category_path": [
"Vintage",
"Home Decor"
],
"category_path_ids": [
69150437,
68890874
],
"materials": [],
"shop_section_id": 7519142,
"featured_rank": null,
"state_tsz": 1432318834,
"url": "https://www.etsy.com/listing/219439470/flying-wooden-folk-art-seagull?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 27,
"num_favorers": 17,
"shipping_template_id": null,
"processing_min": 3,
"processing_max": 5,
"who_made": "someone_else",
"is_supply": "false",
"when_made": "before_1996",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": null,
"is_private": false,
"recipient": "unisex_adults",
"occasion": "housewarming",
"style": [
"Primitive",
"Rustic"
],
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"suggested_taxonomy_id": 1002,
"taxonomy_path": [
"Home & Living",
"Home Décor"
],
"used_manufacturer": false
},
{
"listing_id": 219570447,
"state": "active",
"user_id": 57049901,
"category_id": 68891802,
"title": "4-INSTANT-Machine Embroidery Design pack Download~roses & text pack~Mother&#39;s Rose Garden~pretty flower~mom mother day~love~MaryMeridius 4x4",
"description": "This is a design pack of 4 roses and 1 &quot;mother&quot; text. Each design is unique and can not find anywhere else. Each rose was designed for a 100x100mm hoop. The word mother will fit if you would like to add it. \n\nGet creative.. The roses are each a little different. You can arrange them and use different color thread to sew up something beautiful. I cant wait to see what you make!! \n\nThe instant download contains the following formats: hus, pes, pec, pcs, dst and jef\n\nIf you prefer a different format just let me know. \n\nThank you for looking!!\n\nYou may not resell these embroidery designs, however you may stitch them out and sell as a finished item. :)",
"creation_tsz": 1432661376,
"ending_tsz": 1443288576,
"original_creation_tsz": 1421949757,
"last_modified_tsz": 1432661376,
"price": "3.00",
"currency_code": "USD",
"quantity": 19,
"tags": [
"mom",
"mother",
"love",
"memory",
"rose garden",
"memorial",
"mothers day",
"birthday",
"christmas",
"mary meridius",
"embroidery design",
"embroidery",
"machine embroidery"
],
"category_path": [
"Art",
"Fiber Art"
],
"category_path_ids": [
68887312,
68891802
],
"materials": [],
"shop_section_id": 16644298,
"featured_rank": null,
"state_tsz": 1432661370,
"url": "https://www.etsy.com/listing/219570447/4-instant-machine-embroidery-design-pack?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 29,
"num_favorers": 0,
"shipping_template_id": null,
"processing_min": null,
"processing_max": null,
"who_made": "i_did",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": null,
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": true,
"is_digital": true,
"file_data": "1 ZIP",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 82,
"taxonomy_path": [
"Art & Collectibles",
"Fiber Arts"
],
"used_manufacturer": false
},
{
"listing_id": 198830672,
"state": "active",
"user_id": 24215498,
"category_id": 68900036,
"title": "Rustic Birdhouse in Barn Red Handmade",
"description": "The Chicken Coop! This rustic barn red birdhouse I made  from reclaimed wood and found objects. It has an enameled brass chicken and a vintage brass handle perch. It is all pine wood painted and distressed in barn red with reclaimed wood siding roof. \r\nAll my birdhouses are unique and no two are ever alike.\r\n It could go either outside or in your home. Set it on a shelf or attach it to a fence or hang it in a tree.\r\nIt measures 8&quot; wide and 14&#39; at tallest point.",
"creation_tsz": 1432661371,
"ending_tsz": 1443288571,
"original_creation_tsz": 1407245631,
"last_modified_tsz": 1432661371,
"price": "32.00",
"currency_code": "USD",
"quantity": 1,
"tags": [
"birdhouse",
"rustic",
"garden decor",
"outdoor",
"recycled art",
"rustic birdhouse",
"handmade",
"bird house",
"salvage",
"distressed",
"one of a kind",
"barn red",
"chickens"
],
"category_path": [
"Housewares",
"Outdoor",
"Garden Decor"
],
"category_path_ids": [
69150425,
68891508,
68900036
],
"materials": [
"pine",
"paint",
"screws",
"metal"
],
"shop_section_id": 13665251,
"featured_rank": null,
"state_tsz": 1431192038,
"url": "https://www.etsy.com/listing/198830672/rustic-birdhouse-in-barn-red-handmade?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 105,
"num_favorers": 19,
"shipping_template_id": null,
"processing_min": 1,
"processing_max": 3,
"who_made": "i_did",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": null,
"is_private": false,
"recipient": "birds",
"occasion": "housewarming",
"style": [
"Rustic",
"Cottage Chic"
],
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 1957,
"taxonomy_path": [
"Home & Living",
"Outdoor & Gardening",
"Feeders & Birdhouses",
"Birdhouses"
],
"used_manufacturer": false
},
{
"listing_id": 160028134,
"state": "active",
"user_id": 8080206,
"category_id": 68892008,
"title": "Cast  Iron Squirrel Welcome Sign - Plaque Painted  in Dark Coco Brown",
"description": "Cast Iron Squirrel Welcome Sign, it measures about 4 1/2 inches tall and about 5 inches wide. \r\n\r\n\r\nPLEASE READ SHOP POLICIES\r\n\r\n****ONLY SHIPS IN THE U.S, NOT INTERNATIONAL, SORRY.****\r\n\r\n****ALL ITEMS WILL BE SHIPPED ONCE PAYMENT IS RECEIVED****\r\n\r\n****ALL SALES ARE FINAL****",
"creation_tsz": 1432661367,
"ending_tsz": 1443288567,
"original_creation_tsz": 1376865607,
"last_modified_tsz": 1432661367,
"price": "16.95",
"currency_code": "USD",
"quantity": "1",
"tags": [
"shabby chic",
"romantic country",
"cast iron",
"spring chic",
"squirrel",
"nut",
"garden",
"outdoors",
"welcome sign",
"wall decor",
"apartment",
"store shop",
"door"
],
"category_path": [
"Housewares",
"Home Decor"
],
"category_path_ids": [
69150425,
68892008
],
"materials": [
"recycled cast iron paint"
],
"shop_section_id": 6556853,
"featured_rank": null,
"state_tsz": 1422664864,
"url": "https://www.etsy.com/listing/160028134/cast-iron-squirrel-welcome-sign-plaque?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 389,
"num_favorers": 96,
"shipping_template_id": null,
"processing_min": 1,
"processing_max": 2,
"who_made": "i_did",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": null,
"is_private": false,
"recipient": null,
"occasion": null,
"style": [
"Country Western",
"Folk"
],
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 1029,
"taxonomy_path": [
"Home & Living",
"Home Décor",
"Wall Décor",
"Wall Hangings"
],
"used_manufacturer": false
},
{
"listing_id": 232687688,
"state": "active",
"user_id": 16647277,
"category_id": 69150433,
"title": "Flower Ribbon / Flower Grosgrain Ribbon / Floral Ribbon / Floral Grosgrain Ribbon / Boho Ribbon / Hair Ribbon / 7/8&quot; Ribbon by the Yard",
"description": "Flower ribbon, boho floral grosgrain in 7/8&quot; width. \n\nVery nice quality, single sided grosgrain ribbon. \nAvailable in increments of 1, 3, 5 or 10 yards . \n\nGreat to use for hair bows, sewing projects, key fobs, scrapbooking, crafts and more!\n\n\nView more of my ribbons here &gt; http://etsy.me/1E7k20e\n\nShipping is via USPS First Class and includes a tracking number.\nThanks for looking!",
"creation_tsz": 1432661357,
"ending_tsz": 1443288557,
"original_creation_tsz": 1431054073,
"last_modified_tsz": 1432661357,
"price": "1.10",
"currency_code": "USD",
"quantity": 1,
"tags": [
"grosgrain ribbon",
"hair bow ribbon",
"hair ribbon",
"hair bow supplies",
"key fob ribbon",
"ribbon by the yard",
"flower garden ribbon",
"floral grosgrain",
"flower ribbon",
"boho ribbon",
"small flower ribbon",
"flower grosgrain",
"floral ribbon"
],
"category_path": [
"Supplies"
],
"category_path_ids": [
69150433
],
"materials": [],
"shop_section_id": 14960278,
"featured_rank": null,
"state_tsz": 1432656665,
"url": "https://www.etsy.com/listing/232687688/flower-ribbon-flower-grosgrain-ribbon?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 16,
"num_favorers": 2,
"shipping_template_id": null,
"processing_min": 1,
"processing_max": 2,
"who_made": "someone_else",
"is_supply": "true",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": true,
"taxonomy_id": 562,
"taxonomy_path": [
"Craft Supplies & Tools"
],
"used_manufacturer": false
},
{
"listing_id": 181048702,
"state": "active",
"user_id": 7796103,
"category_id": 69172099,
"title": "In The Beginning Garden Twist fabric nearly 2 yards",
"description": "This is a Garden Twist classic tone on tone print featuring sage green leaves on a light sage background.  Made by In The Beginning, it coordinates well with their floral bouquets.  Nearly two yards, measuring 69&quot; x 42&quot;.",
"creation_tsz": 1432661353,
"ending_tsz": 1443288553,
"original_creation_tsz": 1393635503,
"last_modified_tsz": 1432661353,
"price": "16.00",
"currency_code": "USD",
"quantity": 1,
"tags": [
"Quilt fabric",
"Sage green",
"Tone on tone",
"Garden Twist",
"In The Beginning",
"Leaves",
"Coordinates"
],
"category_path": [
"Supplies",
"Fabric",
"Cotton"
],
"category_path_ids": [
69150433,
68888310,
69172099
],
"materials": [
"All cotton"
],
"shop_section_id": 14537882,
"featured_rank": null,
"state_tsz": 1432247437,
"url": "https://www.etsy.com/listing/181048702/in-the-beginning-garden-twist-fabric?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 40,
"num_favorers": 1,
"shipping_template_id": null,
"processing_min": 1,
"processing_max": 1,
"who_made": "someone_else",
"is_supply": "true",
"when_made": "1996_1999",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": null,
"is_private": false,
"recipient": null,
"occasion": null,
"style": [
"Traditional",
"Cottage Chic"
],
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"suggested_taxonomy_id": 574,
"taxonomy_path": [
"Craft Supplies & Tools",
"Fabric"
],
"used_manufacturer": false
},
{
"listing_id": 232092872,
"state": "active",
"user_id": 14570188,
"category_id": 68888310,
"title": "Bugapalooza Ladybugs on Black from In The Beginning Fabrics",
"description": "This listing is for Bugapalooza Ladybugs on Black from In The Beginning Fabrics.\n\n100% Cotton\n\n*Multiple Yards will be cut as one continuous piece*\n\nLIKE us on Facebook for Fabric Specials & Giveaways:\nwww.Facebook.com/StitchStashDiva\n\nIMPORTANT SHIPPING INFORMATION - PLEASE NOTE:\n\nWe automatically ship all fabric orders via Priority Mail or FedEx Express. If you purchase a total of TWO YARDS OR LESS and prefer First Class Shipping (and a refund of the excess shipping fees) please leave a note at checkout &quot;First Class Shipping&quot; and we will process your shipping refund as soon as your fabric ships.\n\nPlease see our shop policies for details on First Class Shipping, expected delivery time, and adding insurance to your order. Thank you!\n\nhttp://www.etsy.com/shop/StitchStashDiva/policy?ref=shopinfo_policies_leftnav\n\nINTERNATIONAL CUSTOMERS - Shipping Rate is a flat fee for up to 11 yards of cotton.\n\n*************************************************************\nFabric is cut &quot;straight&quot; according to the way the fabric is folded and started on the board by the manufacturer - which is not always symmetrical to the design. When purchasing a &quot;directional or print fabric&quot; meaning any fabric that is not an all over, random design, we recommend you purchase a little extra so that you may straighten and place the design in your project exactly how you would like. For Example: If you purchase one of our &quot;Remix Oval&quot; fabrics and need exactly a 1/4 yard, please purchase 1/3 yard cut (4 extra inches of fabric) so that you have the wiggle room to &quot;fussy cut&quot; a perfectly straight line according to where you would like to start the pattern in your project - at the top of an oval, middle of an oval, or wherever you prefer. &quot;Fussy Cut&quot; is a sewing term for cutting with the design or pattern, not necessarily with the grain of the fabric. For your shopping convenience, cotton fabrics are each listed in many small increments so you may select the size that is best for your project. Please convo us if you have any questions. Thank You!\n*************************************************************",
"creation_tsz": 1432661322,
"ending_tsz": 1443288522,
"original_creation_tsz": 1430630117,
"last_modified_tsz": 1432661322,
"price": "3.00",
"currency_code": "USD",
"quantity": 3,
"tags": [
"Bugapalooza",
"lady bugs",
"ladybugs",
"insects",
"plants",
"garden",
"black and red",
"bugs",
"StitchStashDiva",
"kids fabric",
"In the beginning",
"ladybugs on black"
],
"category_path": [
"Supplies",
"Fabric"
],
"category_path_ids": [
69150433,
68888310
],
"materials": [
"cotton fabric"
],
"shop_section_id": 10796197,
"featured_rank": null,
"state_tsz": 1430630117,
"url": "https://www.etsy.com/listing/232092872/bugapalooza-ladybugs-on-black-from-in?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 10,
"num_favorers": 2,
"shipping_template_id": 3359332,
"processing_min": 1,
"processing_max": 2,
"who_made": "someone_else",
"is_supply": "true",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": true,
"taxonomy_id": 574,
"taxonomy_path": [
"Craft Supplies & Tools",
"Fabric"
],
"used_manufacturer": false
},
{
"listing_id": 176703296,
"state": "active",
"user_id": 42942389,
"category_id": 68887430,
"title": "Red Cedar Royal English 4ft. Outdoor Porch Swing",
"description": "- The Royal English styling brings highlights a classical whimsical themed backrest. \n- It is handcrafted from solid western red cedar. \n- Optional stain finish with Natural-Kote, a soy-based wood stain that will rejuvenate, preserve and protect your furniture. \n- The shown cushion and pillows are not included but are available. \n- Contact me for pricing. \n- Outside dimensions: 52W x 27D x 27H in. \n- Assembly required.\n\nRef# 412C",
"creation_tsz": 1432661306,
"ending_tsz": 1443288506,
"original_creation_tsz": 1390415973,
"last_modified_tsz": 1432661306,
"price": "209.00",
"currency_code": "USD",
"quantity": 5,
"tags": [
"porch swing",
"hanging swing",
"outdoor swing",
"patio swing",
"garden swing",
"front porch swing",
"outdoor porch swing",
"wood swing",
"wooden swing",
"painted swing",
"white swing",
"black swing"
],
"category_path": [
"Furniture"
],
"category_path_ids": [
68887430
],
"materials": [
"Red cedar"
],
"shop_section_id": 14887109,
"featured_rank": null,
"state_tsz": 1431885643,
"url": "https://www.etsy.com/listing/176703296/red-cedar-royal-english-4ft-outdoor?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 333,
"num_favorers": 38,
"shipping_template_id": null,
"processing_min": 5,
"processing_max": 10,
"who_made": "i_did",
"is_supply": "false",
"when_made": "made_to_order",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": true,
"taxonomy_id": 967,
"taxonomy_path": [
"Home & Living",
"Furniture"
],
"used_manufacturer": false
},
{
"listing_id": 176700328,
"state": "active",
"user_id": 42942389,
"category_id": 68887430,
"title": "Red Cedar Traditional English 4ft. Outdoor Porch Swing",
"description": "- Looking for mission syling, then the Traditional English swing is for you! \n- It is handcrafted from solid western red cedar. \n- Optional stain finish with Natural-Kote, a soy-based wood stain that will rejuvenate, preserve and protect your furniture. \n- The shown cushion and pillows are not included but are available. \n- Contact me for pricing. \n- Outside dimensions: 52W x 27D x 27H in. \n- Assembly required.\n\nRef# 402C",
"creation_tsz": 1432661305,
"ending_tsz": 1443288505,
"original_creation_tsz": 1390414619,
"last_modified_tsz": 1432661305,
"price": "204.00",
"currency_code": "USD",
"quantity": 5,
"tags": [
"porch swing",
"hanging swing",
"outdoor swing",
"patio swing",
"garden swing",
"front porch swing",
"outdoor porch swing",
"wood swing",
"wooden swing",
"painted swing",
"white swing",
"black swing"
],
"category_path": [
"Furniture"
],
"category_path_ids": [
68887430
],
"materials": [
"Red cedar"
],
"shop_section_id": 14887109,
"featured_rank": null,
"state_tsz": 1431885642,
"url": "https://www.etsy.com/listing/176700328/red-cedar-traditional-english-4ft?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 731,
"num_favorers": 55,
"shipping_template_id": null,
"processing_min": 5,
"processing_max": 10,
"who_made": "i_did",
"is_supply": "false",
"when_made": "made_to_order",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": true,
"taxonomy_id": 967,
"taxonomy_path": [
"Home & Living",
"Furniture"
],
"used_manufacturer": false
},
{
"listing_id": 101516102,
"state": "active",
"user_id": 14654586,
"category_id": 68897138,
"title": "Glass Round Pendant Abstract Swirl Tree Nature Garden Bezel",
"description": "Elegant circle 1 inch\r\nPendant will in in a Lead Free Bezel\r\nFlat Back\r\nExtremely Clear and Extremely Smooth\r\n\r\nCover will clear Glaze!\r\n\r\nFree Ball Chiain\r\n\r\nImaged is sealed with a clear glaze.\r\n\r\nFree USA shipping!",
"creation_tsz": 1432661296,
"ending_tsz": 1443288496,
"original_creation_tsz": 1338998660,
"last_modified_tsz": 1432661296,
"price": "7.50",
"currency_code": "USD",
"quantity": "1",
"tags": [
"tile",
"image",
"metal",
"ball chain",
"pendant",
"red",
"sterling silver",
"nature",
"swirl tree",
"abstract"
],
"category_path": [
"Jewelry",
"Pendant",
"Glass"
],
"category_path_ids": [
68887482,
69152399,
68897138
],
"materials": [
"glass"
],
"shop_section_id": 8067082,
"featured_rank": null,
"state_tsz": 1420908633,
"url": "https://www.etsy.com/listing/101516102/glass-round-pendant-abstract-swirl-tree?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 130,
"num_favorers": 15,
"shipping_template_id": null,
"processing_min": null,
"processing_max": null,
"who_made": "collective",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": null,
"is_private": false,
"recipient": "unisex_adults",
"occasion": "halloween",
"style": null,
"non_taxable": true,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"suggested_taxonomy_id": 1229,
"taxonomy_path": [
"Jewelry",
"Necklaces",
"Pendants"
],
"used_manufacturer": false
},
{
"listing_id": 163109621,
"state": "active",
"user_id": 23905325,
"category_id": 69150433,
"title": "Victorian Garden on Clear Czech Glass Button 32mm",
"description": "Green and Yellow Accents Makes this Victorian Stained Glass Button Bloom with Floral and Leaf Motif",
"creation_tsz": 1432661288,
"ending_tsz": 1443288488,
"original_creation_tsz": 1379526708,
"last_modified_tsz": 1432661288,
"price": "7.00",
"currency_code": "USD",
"quantity": 1,
"tags": [],
"category_path": [
"Supplies"
],
"category_path_ids": [
69150433
],
"materials": [],
"shop_section_id": 13691256,
"featured_rank": null,
"state_tsz": 1432303841,
"url": "https://www.etsy.com/listing/163109621/victorian-garden-on-clear-czech-glass?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 63,
"num_favorers": 16,
"shipping_template_id": 1767872393,
"processing_min": 1,
"processing_max": 3,
"who_made": "someone_else",
"is_supply": "true",
"when_made": "before_1996",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": null,
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 744,
"taxonomy_path": [
"Craft Supplies & Tools",
"Sewing & Needlecraft Supplies",
"Buttons & Fasteners"
],
"used_manufacturer": false
},
{
"listing_id": 228718044,
"state": "active",
"user_id": 30717862,
"category_id": 68900036,
"title": "Customizable Porcelain Plaque, House Number, Door Sign, Name Plate, Door Plate, Name Sign, Address Plaque, Address Sign, Ornaments, outdoor",
"description": "Porcelain plate, Motif: &quot;Ornaments&quot;\n\n...... for your own home or as a perfect gift.\n\nWith purchase please specify desired text, number of font and motif color (not every color is available, please contact me first)\n\nBefore the fire I create a sketch for you ....... more on that in my general business terms and conditions.\nThe signs themselves are produced by porcelain manufacturers, I design, in * ceramic printing process in my own atelier. The decor firing takes place at about 1596 ° F, this makes the signs weather, frost- and UV-resistant.\n* A ceramic printing is only &quot;ceramic&quot;, if the color of oxides or ceramic stains are fired in the glaze with at least 1112° F.\n\nGet an impression of my offer, get some ideas home - Creativity opens hearts.\n\nWhether classic, modern or playful, my motives cover a wide range. Just browse. You might discover something that exactly meets your taste ...... or you have an individual idea of ​​your plate?\nYou have a question? Just get in touch with me, I`m looking forward hearing from you!\n\nQuantity: 1 \nMaterial: Porcelain, Ceramic Decal \nMotiv: Blue Tit\nProduction: : Firing at about 1596 ° F\nPersonalization: Text, Font, Motif Color (not every color is available, please contact me first)\n\n\nDue to the lighting conditions in product photography and different monitor settings, it may happen that the product color is not reproduced authentically.",
"creation_tsz": 1432661286,
"ending_tsz": 1443288486,
"original_creation_tsz": 1428128508,
"last_modified_tsz": 1432661286,
"price": "39.80",
"currency_code": "EUR",
"quantity": 1,
"tags": [
"nameplate",
"doorsign",
"porcelainplate",
"ornament",
"house number",
"door plate",
"name plate",
"noble",
"name sign",
"address plaque",
"address plate",
"address sign",
"sign"
],
"category_path": [
"Housewares",
"Outdoor",
"Garden Decor"
],
"category_path_ids": [
69150425,
68891508,
68900036
],
"materials": [
"Porzellan",
"keramischer Druck",
"porcelain",
"ceramic decal"
],
"shop_section_id": 13782050,
"featured_rank": null,
"state_tsz": 1428563066,
"url": "https://www.etsy.com/listing/228718044/customizable-porcelain-plaque-house?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 13,
"num_favorers": 1,
"shipping_template_id": 10231649077,
"processing_min": 5,
"processing_max": 10,
"who_made": "i_did",
"is_supply": "false",
"when_made": "made_to_order",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": "unisex_adults",
"occasion": null,
"style": [
"Romantik"
],
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": true,
"taxonomy_id": 1116,
"taxonomy_path": [
"Home & Living",
"Outdoor & Gardening",
"Mailboxes"
],
"used_manufacturer": false
},
{
"listing_id": 185618339,
"state": "active",
"user_id": 39681000,
"category_id": 69150425,
"title": "Hand Painted Glass Bottle Olive Oil Dispenser White Flowers Butterflies Hand Painted Glassware Painted Oil Vinegar Soap Dispensers Bottles",
"description": "Bright and beautiful oil bottle (for olive or other oil, vinegar or soap) with dispenser featuring blooming white garden flowers and white butterflies hand painted all the way around with acrylic paint. Makes a great gift for someone special (or, perhaps, yourself). May also be used in decoration as an accent.\n\nThis oil bottle is made in Italy and has a subtle light-green tint. It can hold 16 oz (473 ml). It is 10 inches (25.4 cm) tall without the dispenser and 12 inches (30.5 cm) tall altogether with the dispenser. The width of the bottle is 2 inches (5 cm).\n\nCARE INSTRUCTIONS: This bottle is NOT dishwasher safe, so it should be hand washed only. We recommend hand washing without using harsh chemicals or abrasive materials or objects. Also, do not soak it in hot water.\n\nThis product is in stock and ready to ship within 1-2 business days. We can quickly make any additional quantities of this product, so please get in touch with us to order larger quantities.\n\nIf you have any questions about this product before purchasing or after or if you have any special instructions for us, please do not hesitate to send us a message. We typically respond to all messages by the end of business day. If you&#39;d like us to send this product as a gift to some other address within the United States, please let us know. We can also include a card with your personalized message for the recipient.\n\nPLEASE NOTE: We love custom orders! If you like exquisite unique gifts designed just for you, for someone else or for any special occasion, please do get in touch with us. We&#39;ll thoroughly discuss your specific needs with you - be it specific designs, materials or surfaces, large quantities or just about anything else - to design and create a perfect order to your complete satisfaction. Custom orders may take longer time to fulfill, so please contact us as soon as possible about your specific needs.\n\nFor a sample of completed custom orders, please see our sold products: www.etsy.com/shop/HelensGiftStore/sold\n\nAlso, please see our section Hand Painted Glassware for bottles with other designs: www.etsy.com/shop/HelensGiftStore?section_id=14735444\n\nPlease be sure to check other items in our store: www.etsy.com/shop/HelensGiftStore",
"creation_tsz": 1432661286,
"ending_tsz": 1443288486,
"original_creation_tsz": 1397026440,
"last_modified_tsz": 1432661286,
"price": "24.95",
"currency_code": "USD",
"quantity": 4,
"tags": [
"painted glassware",
"painted glass bottle",
"painted oil bottles",
"hand painted bottles",
"olive oil dispenser",
"hand painted glass",
"handpainted glass",
"white garden flowers",
"white butterflies",
"olive oil bottles",
"painted glass",
"vinegar dispensers",
"soap dispensers"
],
"category_path": [
"Housewares"
],
"category_path_ids": [
69150425
],
"materials": [
"glass bottle",
"nontoxic acrylic paint"
],
"shop_section_id": 14735444,
"featured_rank": null,
"state_tsz": 1412792945,
"url": "https://www.etsy.com/listing/185618339/hand-painted-glass-bottle-olive-oil?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 2671,
"num_favorers": 155,
"shipping_template_id": 2220427900,
"processing_min": 1,
"processing_max": 2,
"who_made": "i_did",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": null,
"is_private": false,
"recipient": "women",
"occasion": "valentines",
"style": [
"One stroke"
],
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 891,
"taxonomy_path": [
"Home & Living"
],
"used_manufacturer": false
},
{
"listing_id": 159128400,
"state": "active",
"user_id": 35786265,
"category_id": 69153219,
"title": "Personalised Wedding Day, Anniversary Gift. Wooden Garden Planters",
"description": "These bespoke wooden are made from treated decking board which will last for many years. They are painted in muted clay and personalised with the name and date of the happy couple painted in black.\r\n\r\nWill make a great wedding or anniversary gift.\r\n\r\nInner size 240mm x 240mm x 240mm\r\n\r\nThey are made by hand to a high quality.  The legs are screwed on (not nailed like some others) and are fully lined.",
"creation_tsz": 1432661197,
"ending_tsz": 1443288397,
"original_creation_tsz": 1376036897,
"last_modified_tsz": 1432661207,
"price": "25.00",
"currency_code": "GBP",
"quantity": 10,
"tags": [
"Wedding",
"Anniversary",
"Wood",
"Planters",
"Garden",
"Bespoke",
"Personalised"
],
"category_path": [
"Plants and Edibles",
"Plant"
],
"category_path_ids": [
68887346,
69153219
],
"materials": [
"Wood",
"Decking",
"Timber"
],
"shop_section_id": 14031556,
"featured_rank": null,
"state_tsz": 1432576227,
"url": "https://www.etsy.com/listing/159128400/personalised-wedding-day-anniversary?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 262,
"num_favorers": 5,
"shipping_template_id": null,
"processing_min": 3,
"processing_max": 5,
"who_made": "i_did",
"is_supply": "false",
"when_made": "made_to_order",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": null,
"is_private": false,
"recipient": null,
"occasion": "wedding",
"style": null,
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": true,
"taxonomy_id": 1105,
"taxonomy_path": [
"Home & Living",
"Outdoor & Gardening"
],
"used_manufacturer": false
},
{
"listing_id": 234774676,
"state": "active",
"user_id": 39880638,
"category_id": 68891508,
"title": "Old Wooden Tool Box, Large Vintage Wood Tool Tray",
"description": "This is a large rustic well-worn wooden tool carrier with wonderful vintage wear, scuffs, scratches, spatters and dings that add to its charm. The primitive wood box has a center divider handle and a one board bottom. This wooden tool carrier transcends utility to become an artistic planter, book holder or garden tools carrier, many possibilities for a large heavy duty wooden box.  The vintage tool box is solid, the handle hold is chipped, the wood box has timeless patina, please review the photos for condition information. The wood tool box measures 31 1/2” long by 13” wide by 5 5/8” high at the ends, about 8 1/2&quot; at the handle. The old tool tray weighs about 10 lbs.\n\nShipping is calculated from the Maine to west coast, please feel free to request a shipping quote.",
"creation_tsz": 1432661180,
"ending_tsz": 1443288380,
"original_creation_tsz": 1432653319,
"last_modified_tsz": 1432661180,
"price": "68.00",
"currency_code": "USD",
"quantity": 1,
"tags": [
"garden planter",
"tool tray",
"wooden tool box",
"vintage",
"wood tool box",
"tool carrier",
"primitive tool box",
"wood tote",
"tool caddy",
"carpenter",
"rustic wood tool box",
"primitive tool caddy",
"rustic flower box"
],
"category_path": [
"Housewares",
"Outdoor"
],
"category_path_ids": [
69150425,
68891508
],
"materials": [
"Wood"
],
"shop_section_id": 14576025,
"featured_rank": null,
"state_tsz": 1432661152,
"url": "https://www.etsy.com/listing/234774676/old-wooden-tool-box-large-vintage-wood?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 0,
"num_favorers": 0,
"shipping_template_id": null,
"processing_min": 1,
"processing_max": 3,
"who_made": "someone_else",
"is_supply": "false",
"when_made": "1940s",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": [
"Cottage Chic",
"Rustic"
],
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 1109,
"taxonomy_path": [
"Home & Living",
"Outdoor & Gardening",
"Garden Boxes"
],
"used_manufacturer": false
},
{
"listing_id": 234761687,
"state": "active",
"user_id": 5621875,
"category_id": 69150425,
"title": "SIZE 14-16 The Mama San Mamasan Kappogi Full Coverage Smock Apron in Flower Garden on Green Size Medium (14-16)",
"description": "Are you a bit messy in the kitchen? \n\nThis is the apron for you!\n\nThis full coverage apron will protect you from the flying flour and splattering bacon grease! Made in the traditional Mama San style, this smock apron covers the full front and sleeve, and ties in the back at neck and waist.\n\nMy aprons are always made from preshrunk cotton fabric, and feature lots of topstitching to keep their crisp appearance after washing. All exposed seams are serged to prevent fraying. This apron features two patch pockets on front. This apron was made from a repro pattern originally released in the 1970&#39;s.  Apron has side seams with a bit of flare for wearing ease.\n\nApron is sized Medium, to a fit 14-16 sized woman (36-38&quot;) bust. Finished garment measurement at bust is 45 1/2&quot; for design and wearing ease. Length from shoulder seam at neck to hem is 32 1/2&quot;. This apron is generously sized, please check measurements against an apron you enjoy wearing.\n\n\nApron is ready for immediate shipment. I am continually making aprons, please check back for more prints and styles to come.\n\nProudly made in the USA of a Joan Kessler Print for Concord Fabrics, fabric produced in the USA.",
"creation_tsz": 1432661169,
"ending_tsz": 1443288369,
"original_creation_tsz": 1432661169,
"last_modified_tsz": 1432661532,
"price": "35.00",
"currency_code": "USD",
"quantity": 1,
"tags": [
"mama san",
"mamasan",
"full coverage",
"goodyboppers",
"smock",
"ladies",
"cooking",
"kappogi",
"apron",
"full coverage apron",
"smock apron",
"japanese apron",
"floral print apron"
],
"category_path": [
"Housewares"
],
"category_path_ids": [
69150425
],
"materials": [
"cotton",
"fabric"
],
"shop_section_id": 5361976,
"featured_rank": null,
"state_tsz": 1432661169,
"url": "https://www.etsy.com/listing/234761687/size-14-16-the-mama-san-mamasan-kappogi?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 0,
"num_favorers": 0,
"shipping_template_id": null,
"processing_min": 1,
"processing_max": 1,
"who_made": "i_did",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": "women",
"occasion": "mothers_day",
"style": null,
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 1082,
"taxonomy_path": [
"Home & Living",
"Kitchen & Dining",
"Linens",
"Aprons"
],
"used_manufacturer": false
},
{
"listing_id": 234755397,
"state": "active",
"user_id": 35447989,
"category_id": 69153219,
"title": "Welcome Friends Shabby Chic Sign",
"description": "Pretty little sign to welcome your friends, great for gift-giving!\n\nFinished on 3/4&quot; pine, measures approx. 6&quot;x12&quot;, soft white on a turquoise background and lightly distressed.\n\nMade in Canada, ready to ship in one week. US customers, please convo first, if you&#39;d like to confirm that the stated shipping includes delivery confirmation.\n\nWe gladly combine shipping on multiple items.",
"creation_tsz": 1432661157,
"ending_tsz": 1443288357,
"original_creation_tsz": 1432657897,
"last_modified_tsz": 1432661157,
"price": "15.00",
"currency_code": "CAD",
"quantity": 1,
"tags": [
"Welcome Friends",
"Welcome sign",
"Shabby chic",
"handpainted sign",
"indoor signs",
"outdoor signs",
"garden signs",
"IzzyB signs",
"IzzyB Vintage Me",
"Rustic Signs",
"House warming gift",
"Turquoise",
"Victorian signs"
],
"category_path": [
"Plants and Edibles",
"Plant"
],
"category_path_ids": [
68887346,
69153219
],
"materials": [
"Pine",
"paint",
"wire hanger"
],
"shop_section_id": null,
"featured_rank": null,
"state_tsz": 1432657897,
"url": "https://www.etsy.com/listing/234755397/welcome-friends-shabby-chic-sign?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 0,
"num_favorers": 0,
"shipping_template_id": null,
"processing_min": 5,
"processing_max": 10,
"who_made": "i_did",
"is_supply": "false",
"when_made": "made_to_order",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 1105,
"taxonomy_path": [
"Home & Living",
"Outdoor & Gardening"
],
"used_manufacturer": false
},
{
"listing_id": 234788242,
"state": "active",
"user_id": 35447989,
"category_id": 68900036,
"title": "Patio Rules Handpainted Sign",
"description": "Put your feet up on the patio, and relax!\n\nFinished on 3/4&quot; pine, measures approx. 12&quot;x24&quot;, ready to hang indoors or out.\n\nMade in Canada, ready to ship in one week. US customers, please confirm that stated shipping includes delivery confirmation by sending us a convo.\n\nWe gladly combine shipping costs on multiple items, just convo us for a quote!",
"creation_tsz": 1432661156,
"ending_tsz": 1443288356,
"original_creation_tsz": 1432660644,
"last_modified_tsz": 1432661156,
"price": "40.00",
"currency_code": "CAD",
"quantity": 1,
"tags": [
"Patio Rules Sign",
"Patio Decor",
"Porch Signs",
"handpainted signs",
"IzzyB signs",
"IzzyB Vintage Me",
"Welcome Signs",
"Summer Signs",
"Outddor signs",
"Garden Art",
"Shabby Chic",
"Typography",
"Made in Canada"
],
"category_path": [
"Housewares",
"Outdoor",
"Garden Decor"
],
"category_path_ids": [
69150425,
68891508,
68900036
],
"materials": [
"Pine",
"paint",
"wire hanger"
],
"shop_section_id": 17150603,
"featured_rank": null,
"state_tsz": 1432660644,
"url": "https://www.etsy.com/listing/234788242/patio-rules-handpainted-sign?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 0,
"num_favorers": 0,
"shipping_template_id": null,
"processing_min": 5,
"processing_max": 10,
"who_made": "i_did",
"is_supply": "false",
"when_made": "made_to_order",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 1118,
"taxonomy_path": [
"Home & Living",
"Outdoor & Gardening",
"Patio Furniture"
],
"used_manufacturer": false
},
{
"listing_id": 234761595,
"state": "active",
"user_id": 10638816,
"category_id": 68900036,
"title": "Woodsy Warrior Candle - Aromatherapy Soy Massage Candle 13 oz",
"description": "This Eco-Soy based candle has a very similar essential oil blend to the Woodsy Warrior product line - a very purposeful summer aromatherapy blend that repels unwanted insects without deterring the beneficial ones that help help pollinate our native plants.\n\nThe candle comes with 10 oz of wax in a resealable glass jar that is convenient for repeat outdoor use, on patios, decks, picnics, BBQs, car-camping, etc. - although it is a little heavy for multi-day backpacking trips.  When the wick gets less than 1/2&quot; tall, discontinue lighting and place in a double boiler with water to remove remaining oil and clean with soap and water.  Reuse the bail-clasp jar as needed.\n\nThe aroma is zesty and earthy, the stuff that summer memories are made out of!  Lavender, Citronella, Lemongrass, Cedarwood, Eucalyptus and Peppermint essential oils and no chemical fragrances.  Using a wooden wick, the candle provides a soft glow and medium crackle while it melts quickly into a soft wax, allowing the essential oil aromas to hang in the air and do their magic.\n\nINGREDIENTS: EcoSoya Wax, Lavandula Angustifolia (Lavender) Oil, Cymbopogon Winterianus (Citronella) Oil, Cymbopogon Citratus (Lemongrass), Cedrus Atlantica (Cedarwood) Bark Oil, Eucalyptus Globulus (Eucalyptus) Oil, Mentha Piperita (Peppermint) Leaf Oil.\n\nCAUTION: Burn only on a stable, heat resistant surface away from flammable materials. Keep from drafts. Do not burn candle when wax is less than 1/2 inch from bottom. Never leave candle burning unattended or move while wax is liquid. Keep out of reach of pets and children.",
"creation_tsz": 1432661126,
"ending_tsz": 1443288326,
"original_creation_tsz": 1432661126,
"last_modified_tsz": 1432661126,
"price": "20.09",
"currency_code": "USD",
"quantity": 3,
"tags": [],
"category_path": [
"Housewares",
"Outdoor",
"Garden Decor"
],
"category_path_ids": [
69150425,
68891508,
68900036
],
"materials": [],
"shop_section_id": 16132878,
"featured_rank": null,
"state_tsz": 1432661126,
"url": "https://www.etsy.com/listing/234761595/woodsy-warrior-candle-aromatherapy-soy?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 2,
"num_favorers": 0,
"shipping_template_id": 10172044256,
"processing_min": 1,
"processing_max": 2,
"who_made": "i_did",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": "unisex_adults",
"occasion": "july_4th",
"style": [
"Cottage Chic",
"Woodland"
],
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 1117,
"taxonomy_path": [
"Home & Living",
"Outdoor & Gardening",
"Outdoor Lighting"
],
"used_manufacturer": false
},
{
"listing_id": 234761581,
"state": "active",
"user_id": 28058829,
"category_id": 69150393,
"title": "Whimsical Miniature Fairy Garden Tree, Dollhouse, Terrarium- Fairy Home Accessory",
"description": "This whimsical, fairy garden miniature tree will make a big hit in your fairy village! A colorful conversation starter that will brighten any area you place it in. Use in your terrarium, dollhouse courtyard, model railroad, or fairy garden, or by itself on a shelf.\n\n\n7&quot; tall x 4&quot; wide\n\nComes with a removable wire for staking.",
"creation_tsz": 1432661116,
"ending_tsz": 1443288316,
"original_creation_tsz": 1432661116,
"last_modified_tsz": 1432661117,
"price": "13.50",
"currency_code": "USD",
"quantity": 1,
"tags": [
"dolls and miniatures",
"fairy garden tree",
"fairy garden mini",
"miniature accents",
"mini accessories",
"fairy tree",
"whimsical gift",
"unique gift",
"fantasy",
"dollhouse",
"handmade tree",
"home decor",
"miniature tree"
],
"category_path": [
"Toys"
],
"category_path_ids": [
69150393
],
"materials": [
"air dry clay",
"real moss",
"mulberry paper flowers",
"dried flowers",
"flatback pearls"
],
"shop_section_id": 14931995,
"featured_rank": null,
"state_tsz": 1432661116,
"url": "https://www.etsy.com/listing/234761581/whimsical-miniature-fairy-garden-tree?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 0,
"num_favorers": 0,
"shipping_template_id": null,
"processing_min": 1,
"processing_max": 2,
"who_made": "i_did",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": true,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 1798,
"taxonomy_path": [
"Art & Collectibles",
"Dolls & Miniatures",
"Miniatures"
],
"used_manufacturer": false
},
{
"listing_id": 120004088,
"state": "active",
"user_id": 6533848,
"category_id": 68892160,
"title": "Blue, Purple & White Wedding Bouquet with Calla Lilies, Examply Only!! DO NOT PURCHASE",
"description": "This item is an example only! This was a custom bouquet that was previously made if you need something similar, please contact me so we can come up with something special just for you!! DO NOT PURCHASE THIS LISTING!!!\n\nThis beautiful garden bouquet was made with a mix of flowers including blue hydrangeas, purple anemones, lime green hellebores, ivory callas, and lime green roses. With a few small purple flowers stuck in throughout it. This bouquet was finished off with white ribbon and white lace around the top.This was made of all silk flowers! \nIt measures about 22&quot; around, 11&quot; tall and 8&quot; wide.\n\nTo see more of my bouquets I have for sale check here...\nhttp://www.etsy.com/shop/justanns?section_id=6228679\n\nFind me on Facebook for more pictures of my work!!...\nhttp://www.facebook.com/justanns \n\nCheck out my Pinterest Page for more examples of my past work, & wedding inspiration!\nhttp://www.pinterest.com/justanns/bridal-party-flowers/\n\n\n** CUSTOM ORDERS... I can take any type of custom order, Large or Small!! I like to make bouquets that look fresh and colorful. I work quickly and can get things out in about two weeks to a month’s time. Of course it depends on how big the wedding is, and if I need to order things. But once I have everything I get working! (This is all I do for a living :) I can do multiples of most of the items I have on my site, or I can custom make something new and different.  I have lots of companies I order materials & flowers from, so the possibilities are endless. I have many examples of bouquets on my site both fresh and silk to give you an idea of my style. If you don’t see something you like, do not hesitate to send me a photo of something you do like, to see if I can recreate it, I would be glad to try! I love getting new ideas and inspiration from my customers!  I can do a whole wedding party or just a few boutonnieres, so please contact me today!!\n\nThanks for looking!!",
"creation_tsz": 1432661108,
"ending_tsz": 1443288308,
"original_creation_tsz": 1357768308,
"last_modified_tsz": 1432661108,
"price": "85.00",
"currency_code": "USD",
"quantity": 1,
"tags": [
"brides bouquet",
"wedding bouquet",
"bridal bouquet",
"boutonniere",
"calla lily bouquet",
"purple",
"blue",
"lime green",
"outdoor wedding",
"garden wedding",
"flower bouquet",
"floral bouquet",
"custom bouquet"
],
"category_path": [
"Weddings",
"Bouquet"
],
"category_path_ids": [
68887494,
68892160
],
"materials": [
"flowers",
"silk flowers",
"white ribbon",
"lace"
],
"shop_section_id": 6228679,
"featured_rank": null,
"state_tsz": 1429301278,
"url": "https://www.etsy.com/listing/120004088/blue-purple-white-wedding-bouquet-with?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 427,
"num_favorers": 27,
"shipping_template_id": null,
"processing_min": null,
"processing_max": null,
"who_made": "i_did",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": "wedding",
"style": null,
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 1659,
"taxonomy_path": [
"Weddings",
"Decorations",
"Bouquets"
],
"used_manufacturer": false
},
{
"listing_id": 234789132,
"state": "active",
"user_id": 37949861,
"category_id": 69150433,
"title": "Granite Gravel Flakes, Railway Scenic, Gravel, Railway Ballast, Miniature Landscaping, Fairy Garden Supply, Diorama Supply, Diorama",
"description": "A great choice if you think of creating walkways or paths. Perfect in size, precision pebbles for your Fairy Gardens, railroad tracks, gravel roads, crushed rock and stones, hopper loads and coal piles and any miniature landscaping.\n\nAvailable in several colors and sizes, you can mix and match for a superior realistic effect.\n\nScale:\t7 mm to 1 ft – 6.35 mm to 1 ft (O Scale)\nScale ratio: 1:48 to 1:43.5\n\n\nColour: Granite \nCode: 5314\n\nbag of 300 grams (10.58 oz)\n\n\n***Please note: actual color may vary from picture due to computer settings***",
"creation_tsz": 1432661098,
"ending_tsz": 1443288298,
"original_creation_tsz": 1432661098,
"last_modified_tsz": 1432661098,
"price": "1.80",
"currency_code": "EUR",
"quantity": 4,
"tags": [],
"category_path": [
"Supplies"
],
"category_path_ids": [
69150433
],
"materials": [],
"shop_section_id": 14314115,
"featured_rank": null,
"state_tsz": 1432661098,
"url": "https://www.etsy.com/listing/234789132/granite-gravel-flakes-railway-scenic?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 1,
"num_favorers": 0,
"shipping_template_id": null,
"processing_min": 1,
"processing_max": 3,
"who_made": "someone_else",
"is_supply": "true",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": "in",
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 626,
"taxonomy_path": [
"Craft Supplies & Tools",
"General Supplies"
],
"used_manufacturer": false
},
{
"listing_id": 126550357,
"state": "active",
"user_id": 8014213,
"category_id": 69169877,
"title": "2 Vintage 1950s Enamel Apple Charms // 50s 60s Garden Kitsch // Teacher&#39;s Pet",
"description": "2 Vintage 1950&#39;s / 1960s enamelled brass apple kitsch garden charms!! Adorable and rare! These would be great as a pair of novelty 1940s style earrings or wear them as charms on a necklace or bracelet! These are new old stock. Due to age some of their paint has chipped in tiny spots here or there.\r\n\r\nMeasurements:\r\n17mm\r\n\r\nFor more vintage findings:\r\nhttps://www.etsy.com/shop/ifoundgallery?section_id=6613159",
"creation_tsz": 1432661094,
"ending_tsz": 1443288294,
"original_creation_tsz": 1363388068,
"last_modified_tsz": 1432661094,
"price": "6.00",
"currency_code": "USD",
"quantity": 2,
"tags": [
"1940s style",
"farm",
"garden",
"vegetable",
"kitsch",
"novelty",
"charm",
"pendant",
"vintage",
"apple",
"retro school",
"1950s charms",
"60s charms"
],
"category_path": [
"Vintage",
"Supplies",
"Charm"
],
"category_path_ids": [
69150437,
69153885,
69169877
],
"materials": [
"new old stock",
"enamel",
"hand painted",
"brass"
],
"shop_section_id": 6613159,
"featured_rank": null,
"state_tsz": 1363388068,
"url": "https://www.etsy.com/listing/126550357/2-vintage-1950s-enamel-apple-charms-50s?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 120,
"num_favorers": 21,
"shipping_template_id": null,
"processing_min": 1,
"processing_max": 3,
"who_made": "someone_else",
"is_supply": "false",
"when_made": "1950s",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": null,
"is_private": false,
"recipient": null,
"occasion": null,
"style": [
"Mid Century",
"Kitsch"
],
"non_taxable": false,
"is_customizable": true,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"suggested_taxonomy_id": 697,
"taxonomy_path": [
"Craft Supplies & Tools",
"Jewelry & Beading Supplies",
"Charms"
],
"used_manufacturer": false
},
{
"listing_id": 200015419,
"state": "active",
"user_id": 37267998,
"category_id": 68890908,
"title": "By any other name",
"description": "Still just a rose, this piece is12x24 oil on canvas",
"creation_tsz": 1432661084,
"ending_tsz": 1443288284,
"original_creation_tsz": 1408113608,
"last_modified_tsz": 1432661084,
"price": "80.00",
"currency_code": "USD",
"quantity": 1,
"tags": [
"flower",
"floral",
"rose",
"pink rose",
"red rose",
"garden"
],
"category_path": [
"Art",
"Painting"
],
"category_path_ids": [
68887312,
68890908
],
"materials": [
"oil",
"paint",
"oil paint",
"canvas"
],
"shop_section_id": null,
"featured_rank": null,
"state_tsz": 1430359832,
"url": "https://www.etsy.com/listing/200015419/by-any-other-name?utm_source=theironyardteaching&utm_medium=api&utm_campaign=api",
"views": 35,
"num_favorers": 1,
"shipping_template_id": null,
"processing_min": 1,
"processing_max": 2,
"who_made": "i_did",
"is_supply": "false",
"when_made": "2010_2015",
"item_weight": null,
"item_weight_units": null,
"item_length": null,
"item_width": null,
"item_height": null,
"item_dimensions_unit": null,
"is_private": false,
"recipient": null,
"occasion": null,
"style": null,
"non_taxable": false,
"is_customizable": false,
"is_digital": false,
"file_data": "",
"language": "en-US",
"has_variations": false,
"taxonomy_id": 105,
"taxonomy_path": [
"Art & Collectibles",
"Painting"
],
"used_manufacturer": false
}
],
"params": {
"limit": 25,
"offset": 0,
"page": null,
"keywords": "garden",
"sort_on": "created",
"sort_order": "down",
"min_price": null,
"max_price": null,
"color": null,
"color_accuracy": 0,
"tags": null,
"category": null,
"location": null,
"lat": null,
"lon": null,
"region": null,
"geo_level": "city",
"accepts_gift_cards": "false",
"translate_keywords": "false"
},
"type": "Listing",
"pagination": {
"effective_limit": 25,
"effective_offset": 0,
"next_offset": 25,
"effective_page": 1,
"next_page": 2
}
}
